sudo: false
language: python
python:
- '3.4'
install:
- pip install -r requirements_for_test.txt
script:
- ./scripts/run_tests.sh
notifications:
  slack:
    rooms:
      secure: NmQ1Nh1/HW8kpaCRz7MSQ3FpN5FQsQdZaxjg4j393bptRveMZL6wkvfSqZYtSOYOkwYfTYWGi3q4DfC1BTjEvacsTi9Hz/Y/6z56vlNjPmYSAz2gN9ZcH1cSmtzm6loTExbi9VIWUTPuPmzVYCCRvQB8hNMfuaX/1/139vWpKEpWc+U7sH8jDcgIdDjBxDiXY1NKYHYeG340jc4Jw6MWvHB8gCSU1mIX3PsLUhv1cENR0uCPyaf4F1POazWI3dblbFOTjN7hqL8rFJq4znC+1tIL1X9fbrFL4bSajcygup6KIggLF4op2v9C7Ip+xI+hUcZIj8IvizkqqryMcCcJ+3N1ny1z4lHw/753kfYsIbdxpaXeRxRFm3tNsti5+9qL7ibSBamRmIYGFxnRb3Bb2twp6tRPEZgWX7fl4j85bDZez95/D7+9m/1D2Ipx2FtKJ0U5/2Q0ZA9HHBOfx0iZl6zG/X4oihZNLQr0KmAsYtdHrO7USfFvYy1Itqk9HSDFpkJwDpzZKOVZrhXBmdQijToGzWPWNQJUYZmb3m8uVMt2Rs7vTNzM9Y/XrulBZ2/NLHurwsvFZTx/IIiEll1HtWVJ25awYOYoQUCvyo+IuY0MvDzarpcgl5UkSJotIvVVCvulFbNmfinv9YWeDf42NwUsVScY+lczLHAzbQpW1IE=
