sudo: false
language: python
python:
- '3.4'
install:
- pip install -r requirements_for_test.txt
script:
- ./scripts/run_tests.sh
notifications:
  slack:
    rooms:
      secure: NmQ1Nh1/HW8kpaCRz7MSQ3FpN5FQsQdZaxjg4j393bptRveMZL6wkvfSqZYtSOYOkwYfTYWGi3q4DfC1BTjEvacsTi9Hz/Y/6z56vlNjPmYSAz2gN9ZcH1cSmtzm6loTExbi9VIWUTPuPmzVYCCRvQB8hNMfuaX/1/139vWpKEpWc+U7sH8jDcgIdDjBxDiXY1NKYHYeG340jc4Jw6MWvHB8gCSU1mIX3PsLUhv1cENR0uCPyaf4F1POazWI3dblbFOTjN7hqL8rFJq4znC+1tIL1X9fbrFL4bSajcygup6KIggLF4op2v9C7Ip+xI+hUcZIj8IvizkqqryMcCcJ+3N1ny1z4lHw/753kfYsIbdxpaXeRxRFm3tNsti5+9qL7ibSBamRmIYGFxnRb3Bb2twp6tRPEZgWX7fl4j85bDZez95/D7+9m/1D2Ipx2FtKJ0U5/2Q0ZA9HHBOfx0iZl6zG/X4oihZNLQr0KmAsYtdHrO7USfFvYy1Itqk9HSDFpkJwDpzZKOVZrhXBmdQijToGzWPWNQJUYZmb3m8uVMt2Rs7vTNzM9Y/XrulBZ2/NLHurwsvFZTx/IIiEll1HtWVJ25awYOYoQUCvyo+IuY0MvDzarpcgl5UkSJotIvVVCvulFbNmfinv9YWeDf42NwUsVScY+lczLHAzbQpW1IE=
env:
  secure: m6xBtTSWXn5Q8Inzo2Gn7PoYKPGM6zt7U6Aq3Tw3JynCclQJU1vt+ildFzyOtbJCBQog4V4c5QS7DBwvQsczhx2swvc4zZMhPY+qQWYYgFN6ltxGL76GpGhzX7iWDSE9zMzV2Qxj6VQgVhrjW9I5cny4QpdEVyY1ga5Etb3zPCL/guEhBCdpkcvt3SFYLkYTCFnmIEoZCzCIwz5EXV+ZcZQ6JmD8Pvk67lO0XvS6S5YXz1nJTKt+I4JFB4FcE2KU//m4K+ro+uUR90rQMhhFcEMMIuxxzuloS2hFhfnK7AhK6FYof7Eza3QrVv/S+hB0CIxDoBIeOIEqYDTCi+Y/GY6yyUEC78/riTfBpPqjChQZzQsPWE+VO+qqnJ2Vcg+TjJF2/mqLFPQtBMup2O6/dqqDqj+5wcBYZA+1gMZtZJtTnvseXdF5xfYqNxv9wkGIEa1AUi3jgqK14CPO4mhU/LkR5U2tVHh2cL72Q0T+SsBmQepon0+Ix1gGsLTugbgERxltXT3kS8ZBOYjVRRurEq9afcuLiRwtMDftu1yD/x8xByob1555TNtoYLm7Qs0oiwxFGS7v0f7AUAf3bU4WFmsEbCgpLfPo9vTdl8x0aDmwg5Xd9X0AK54qscGTVxFIACFQ6M5bvXMQLjeZ0tGGoAd1i4MBib2fjGyA4l9s7as=
